### PR TITLE
Fix for issue #7

### PR DESCRIPTION
**Pull request by subblue**
In the test though I’m not sure how to properly catch the failing mock
test and test it’s error state

### CODE REVIEW

**Comment by cedricmessiant** [comment]
it seems good to me !

**Comment by joeellis** [comment]
Oh man I just ran into this exact issue today.  +1 for the fix

**Comment by arnaudbenard** [comment]
I would love to merge that but the tests are not passing. Could you fix them?

EDIT: Let me check how we can test that

**Comment by subblue** [comment]
I couldn't manage to get the test to check for a valid failing test - not sure how to catch the failing test in Mocha and then validate that so that the overall result passes.
Any help would be appreciated :)

**Comment by arnaudbenard** [comment]
I have made a PR with the test fix https://github.com/arnaudbenard/redux-mock-store/pull/14, I will merge that and publish the package

**Comment by arnaudbenard** [comment]
Thank you very much for the help

**Comment by cedricmessiant** [comment]
Thanks !

**Pull request closed without merging**
