### PR TITLE
Add build tests

### PR DESCRIPTION
**Pull request by sbason**
* Update unit tests to run against built main exported version 
* Test ES and CJS builds

Addresses comments in https://github.com/arnaudbenard/redux-mock-store/issues/135

### CODE REVIEW

**Comment by sbason** [comment]
@dmitry-zaets Have you had a chance to look at this?

**Comment by ohtangza** [comment]
@arnaudbenard I think it would be great if we have any CI server integrated with this repo. CircleCI maybe?

**Comment by arnaudbenard** [comment]
There's already circleci running
https://circleci.com/gh/arnaudbenard/redux-mock-store/155?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

@sbason @dmitry-zaets What is the status of the commonjs package change, it looks like it broke a lot of builds. We should either fix it and scrape it. What do you think?

**Comment by ohtangza** [comment]
@arnaudbenard Oh, my bad. It was folded in my view. Thanks for your response.

**Comment by sbason** [comment]
@arnaudbenard @dmitry-zaets #136 should have solved the build problems and this PR tests those builds.

**Comment by jsnavarroc** [comment]
Hello I have a one problem hahaha, whit that, something can help me please!!?
const mockEstado = {
				contactos: {
					nombre: '',
					telefono: '',
					contactos: [mockContacto],
					cargando: false,
					error: '',
				},
			}; 
const store = mockStore(mockEstado);
return store.dispatch( ACCIONES.actualizarContacto(mockContacto.nombre, mockContacto.celular, uid))
**any ideas?
Thank you!!**

**Comment by dmitry-zaets** [comment]
Thanks a lot!

**Pull request merged**
