### PR TITLE
Updated babel to version 6

### PR DESCRIPTION
**Pull request by kylelamse**

### CODE REVIEW

**Comment by kylelamse** [comment]
Why did CI fail at compiling with Babel?  I tested the prepublish script locally and it worked without a hitch.

**Comment by dmitry-zaets** [comment]
Since ["Migrate to Babel 6" Pull request](#53) was closed by maintainer I'm not sure if this one makes any sense.
Build fails on CI because of CI uses Node `v0.10.33` which doesn't have Promises. And it doesn't fail on your machine because you use Node version which already contains Promises.

**Comment by arnaudbenard** [comment]
Maybe we need to add the node version in `circle.yml` https://circleci.com/docs/language-nodejs/#version

This line should polyfill the promise `> mocha --compilers js:babel-core/register --reporter spec test/*.js`

**Comment by arnaudbenard** [comment]
Now that @dmitry-zaets added the node version, you can rebase your branch and check if it works :)

**Comment by kylelamse** [comment]
Ok, I rebased and this should be able to merge successfully now.

**Comment by dmitry-zaets** [comment]
@kylelamse Thanks!

**Pull request merged**
