### PR TITLE
Removed incorrect typings file

### LINKED ISSUE #62: TypeScript support
A lot of recent PRs introduce changes to the TypeScript definition and it causes problems to users. It would be wiser to defer the support to https://github.com/DefinitelyTyped/DefinitelyTyped and make the package more stable.

Let me know what you think.

### PR DESCRIPTION
**Pull request by meandmax**
please use this instead: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/redux-mock-store/redux-mock-store.d.ts

fixes #62

ptal @kinghenne, @arnaudbenard

### CODE REVIEW

**Comment by meandmax** [comment]
hmm ... can't reproduce why circleCI fails with the `babel options`, anybody?

**Comment by dmitry-zaets** [comment]
@meandmax I will take a look

**Comment by arnaudbenard** [comment]
@meandmax @dmitry-zaets I've cleared the cache on CircleCI and it builds now ;)

**Comment by dmitry-zaets** [comment]
@arnaudbenard Thanks!

**Pull request merged**
