### PR TITLE
Improve documentation addressed in #71

### PR DESCRIPTION
**Pull request by ohtangza**
### Summary
Hello, as discussed in #71. I updated our documentation a bit with the aim of clarifying the purpose of this library. Hope this pull request helps new developer here get on their track without being confused.

### Sponsor issue
@arnaudbenard Please update the sponsor section which is now broken. I was trying to fix it, but it seems that `https://app.codesponsor.io` is not accessible (perhaps, it is temporary). Please refer the screenshot below. 

screen shot 2017-12-25 at 4 03 53 pm

**Merry Christmas!!!**

### CODE REVIEW

**Review by dmitry-zaets — APPROVED** [review]

**Comment by dmitry-zaets** [comment]
Thanks a lot for the PR.
Looks good to me.

@arnaudbenard if it looks good to you - please merge.

**Comment by ohtangza** [comment]
@arnaudbenard I resolved the merge conflict which occurred after my last commit.

**Comment by arnaudbenard** [comment]
You can delete code sponsor, it's not available anymore.

**Comment by ohtangza** [comment]
@arnaudbenard Sponsor removed!

**Comment by vekerdyb** [comment]
It would be lovely if this could be merged, it would have saved some time for me this morning! :)

**Comment by ohtangza** [comment]
@vekerdyb I also witnessed that some of my colleagues has been troubled with this as well. Glad to hear that :)

**Pull request merged**
